app:
    resource: '@SalexUserBundle/Controller/'
    type: annotation

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

facebook_login:
    path: /connect/check-facebook

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

avanzu_admin:
    resource: "@AvanzuAdminThemeBundle/Resources/config/routes.yml"

avanzu_admin_profile:
    path: /profile


avanzu_admin_all_notifications:
    path: /notificationsss/

avanzu_admin_show_notification:
    path: /notification/{notifyid}/


fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# image processing bundle
# https://github.com/liip/LiipImagineBundle
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /easyadmin
