# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    access_denied_url:    ~

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        #ROLE_ADMIN:       ROLE_ADMIN
        #ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /login
                always_use_default_target_path: true
                use_referer: true
                success_handler: redirect.after.login
            logout:
                target: /login

            anonymous:    true

            oauth:
                # Declare the OAuth Callback URLs for every resource owner
                # They will be added in the routing.yml file too later
                resource_owners:
                    facebook: "/connect/check-facebook"
                ## Provide the original login path of your application (fosuserroute)
                ## and the failure route when the authentication fails.
                login_path:     /login
                failure_path:   /login

                oauth_user_provider:
                    service: app.fos_user.oauth_provider

    access_control:
    # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }
    #    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    #    - { path: ^/dashboard, role: ROLE_USER }
    #    - { path: ^/list/users, role: ROLE_ADMIN }
    #    - { path: ^/add/reservation, role: ROLE_USER }
