services:
    salex_user.resetting.form.type:
        class: SalexUserBundle\Form\ResettingFormType
        tags:
            - { name: form.type, alias: salex_user_resetting }

    salex_user.profile.form.type:
        class: SalexUserBundle\Form\UserType
        tags:
            - { name: form.type, alias: salex_user_profile }

    salex_user.uvszinhaz_listener:
        class: SalexUserBundle\Utility\Services
        arguments: ['@service_container']

    app.my.form.type:
        class: SalexUserBundle\Form\ReservationFormType # this is your form type class
        arguments:
            - '@salex_user.uvszinhaz_listener' # this is the ID of the service you want to inject
        tags:
            - { name: form.type }


    app.myx.form.type:
          class: SalexUserBundle\Filter\ItemFilterType # this is your form type class
          arguments:
                - '@salex_user.uvszinhaz_listener' # this is the ID of the service you want to inject
          tags:
                - { name: form.type }

    example.listener:
         class: SalexUserBundle\EventListener\ReservationListener
         arguments:
              - '@salex_user.uvszinhaz_listener'
         tags:
               - { name: doctrine.event_listener, event: postLoad }
               - { name: doctrine.event_listener, event: postPersist }